# Set the version of docker compose to use
version: "3.9"

# The containers that compose the project
services:
  app1:
    container_name: nest-socket-redis-be-1
    build:
      context: .
      args:
        ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
        HTTP_PORT: 3000
        APP_NAME: "App 001"
    restart: always
    # ports:
    #   - 3003:3000
    networks:
      - socket-network
    depends_on:
      - redis

  app2:
    container_name: nest-socket-redis-be-2
    build:
      context: .
      args:
        ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
        HTTP_PORT: 3000
        APP_NAME: "App 002"
    restart: always
    networks:
      - socket-network
    depends_on:
      - redis

  app3:
    container_name: nest-socket-redis-be-3
    build:
      context: .
      args:
        ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
        HTTP_PORT: 3000
        APP_NAME: "App 003"
    restart: always
    networks:
      - socket-network
    depends_on:
      - redis

  app4:
    container_name: nest-socket-redis-be-4
    build:
      context: .
      args:
        ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
        HTTP_PORT: 3000
        APP_NAME: "App 004"
    restart: always
    networks:
      - socket-network
    depends_on:
      - redis

  redis:
    image: redis:7.2.1-alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server
    volumes:
      - redis-data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - socket-network
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # redis-commander:
  #   image: rediscommander/redis-commander:latest
  #   environment:
  #     - REDIS_HOSTS=redis://redis:6379
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     - redis

  haproxy:
    build: ./haproxy
    links:
      - app1
      - app2
      - app3
      - app4
    ports:
      - "3030:80"
    networks:
      - socket-network

  # postgres:
  #   image: postgres:14.7
  #   # restart: always
  #   container_name: postgres
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_DB: ${DB_DATABASE}
  #     POSTGRES_USER: ${DB_USERNAME}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     TZ: "GMT"
  #     PGTZ: "GMT"
  #   volumes:
  #     - odidi-db-data:/data/postgres
  #   env_file:
  #     - .env

networks:
  socket-network:
    driver: bridge
    name: socket-network
volumes:
  redis-data: